#ifndef RAYTRACING_REALTIME_APPROXIMATION_APP_H
#define RAYTRACING_REALTIME_APPROXIMATION_APP_H

#include <GL/glew.h>

const GLuint DEFAULT_WINDOW_WIDTH = 800, DEFAULT_WINDOW_HEIGHT = 800;
const char* WINDOW_TITLE = "Raytracing Approximation";

#endif //RAYTRACING_REALTIME_APPROXIMATION_APP_H
